[package]
name = "dog-fetcher"
edition = "2021"
version = "0.1.1"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wasi = { version = "0.13.3", features = ["std"] }
wasmcloud-component = { path = "../../../../crates/component" }
reqwest = { package = "reqwest-wasmcloud", git = "https://github.com/wasmcloud/reqwest/", branch = "master", features = ["stream"]}
